[build]
  command = "npm install"
  publish = "public"  # QUAN TRỌNG: Đổi từ "." thành "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
